### PR TITLE
Repair develop

### LINKED ISSUE #142: Create user not possible form app
**Describe the bug**
I think the reason is that its sending a get request with no user details to the server. this is done from `UserRepositry` `create()`

### PR DESCRIPTION
**Pull request by markusranda**
- Proper response on create new user
- App doesn't crash if there are no organizations to load.
- No longer squeezes the fields when keyboard pops up when creating new account
Closes #142

### CODE REVIEW

File: app/src/main/java/no/ntnu/klubbhuset/ui/userviews/mymemberships/MyMembershipsListFragment.java [hunk 1]
```diff
@@ -65,8 +74,10 @@ public View onCreateView(LayoutInflater inflater, ViewGroup container,
                 recyclerView.setLayoutManager(new GridLayoutManager(context, mColumnCount));
             }
             mViewModel.getClubs().observe(this, clubs -> {
-                if(clubs.getStatus() == Status.SUCCESS) {
+                if (clubs.getStatus() == Status.SUCCESS) {
                     recyclerView.setAdapter(new ClubMembershipRecyclerViewAdapter(clubs.getData(), mListener));
+                } else if (clubs.getStatus() == Status.ERROR) {
+                    Toast.makeText(context, "Couldn't retrieve any organizations", Toast.LENGTH_SHORT).show();
                 }
```
Comment (spiftire) [inline app/src/main/java/no/ntnu/klubbhuset/ui/userviews/mymemberships/MyMembershipsListFragment.java]: Do we need an `else` also?
